### ISSUE TITLE
El programa no agrega datos ni manda mensaje de error

### ISSUE THREAD

**Issue by javatlacati** [aldair11/Libertadores#4]
cuando meto en todos los campos los valores:

* 1
* 2
* 3
* 4
* 5
* 6
* 7

Y doy click en el botón Registrar, aparece el mensaje

> Datos agregados correctamente

PEro el cambio no se ve refleado en la tabla

**Comment by aldair11** [comment]
![image](https://user-images.githubusercontent.com/12890721/49355217-94fcfa80-f694-11e8-9ea1-c76772889781.png)

Colocando esos mismos datos, si los muestra la tabla

**Comment by javatlacati** [comment]
Ya vi que había que darle click a fuerza en el botón de mostrar
