### ISSUE TITLE
Los jugadores se borran al salir del registro de jugadores

### ISSUE THREAD

**Issue by javatlacati** [aldair11/Libertadores#7]
Para reproducir:

* entrar a la pantalla de registro de jugadores
* agregar un jugador
* dar click en el botón salir
* volver a entrar a la pantalla de registro de jugadores

Resultado esperado
---
Que cargue la tabla con el jugador que teníamos agregado

Resultado obtenido
---

Se observa la tabla vacía, sin el jugador

**Comment by aldair11** [comment]
Corregido
